### ISSUE TITLE
global-css.js 的变量似乎没有全部 CSS Variables 化

### ISSUE THREAD

**Issue by yoyo837** [hellof2e/quark-design#237]
比如 `quark-fontSizeBase`、`quark-textSecondaryColor`
```css
:host .quark-actionsheet-title {
  color: quark-textSecondaryColor;
  font-size: quark-fontSizeBase;
  display: flex;
  height: 60px;
  width: 100%;
  justify-content: center;
  align-items: center;
  border-bottom: 0.5px solid #ebedf0;
  text-align: center;
}
```

请问是有意的还是遗漏? 遗漏的话我发个PR补上来.
