### ISSUE TITLE
button自动缩放后里面的loading svg没有跟随缩放, 可能会显得大小差异过大.

### ISSUE THREAD

**Issue by yoyo837** [hellof2e/quark-design#247]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

https://dev-portal.ydmap.cn/srv100436/dev-52.html

当按钮的宽度样式命中源码

```css
:host(:not([size])) {
  font-size: var(--button-font-size, 14px);
}
```

即编译后的

```css
:host(:not([size])) {
  font-size: var(--button-font-size, 3.73333vw);
}
```
, 内部的 loading 仍然是固定的 20px, `size={this.loadingsize ? this.loadingsize : "20"}`, 这个 20px 是否也应该经过统一编译或者怎样能“继承”一下size样式避免出现按钮巨大svg很小的效果:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/6134547/230609670-5f408ec2-5c64-43be-91a3-a53bfd411437.png">

算问题不?
